version: '2'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'task_db'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - task_db:/var/lib/mysql 
      - ./db:/docker-entrypoint-initdb.d/
  app1:
    build: ./serv1
    ports:
      - '11000:5000'
  app2:
    build: ./serv2
    ports:
      - '12000:5000'
    depends_on:
      - db
  
volumes:
  task_db:
