version: '2'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'task_db'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - task_db:/var/lib/mysql 
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - app_network
  app1:
    build: ./serv1  
    environment:
      - "SERVICE_NAME = app1"
      - "ISTIO_META_APP = app1"
      - "ISTIO_META_VERSION=v1"
      - "ISTIO_META_ROUTER = snat"
    labels:
      - "istio.sidecar=true"
    ports:
      - '11000:5000'
    networks:
      - app_network
    depends_on:
      - db
  app2:
    build: ./serv2
    environment:
      - "SERVICE_NAME=app2"
      - "ISTIO_META_APP=app2"
      - "ISTIO_META_VERSION=v1"
      - "ISTIO_META_ROUTER=snat"
    labels:
      - "istio.sidecar=true"
    networks:
      - app_network
    ports:
      - '12000:5000'
    depends_on:
      - db
      - app1
volumes:
  task_db:
networks:
  app_network:
    driver: bridge
