version: '2'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'task_db'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql 
volumes:
  my-db:
